// Stage-2 routed Q4_K integer-WMMA down-projection harness.
//
// Flash shape: M=routed pairs, K=2048, N=4096.  Production first quantizes
// pair-major FP32 post-SwiGLU mid rows to Q8_K, then down consumes Q8_K.  This
// harness copies that quantizer verbatim, repacks Q8_K to the validated Q8_1
// MMQ layout, and compares both WMMA and the shipping-style DP4A fallback to
// an independent host scalar Q4_K x Q8_K reference.  No routing weight or
// SwiGLU belongs in this GEMM: production already folded the weight into mid.
//
// Build with the same ROCM_CFLAGS as q4k_dp4a_baseline_bench.cu.  This file
// intentionally does not include q4k_wmma_routed_bench.cu: its WMMA kernel
// maps pair->token for token-major gate/up activations, whereas down activation
// rows are pair-major and must be indexed by pair directly.
#define main q4k_stage0_unused_main
#include "q4k_dp4a_baseline_bench.cu"
#undef main

#include <climits>

static constexpr uint32_t kUsed=6, kK=2048, kN=4096, kQ8KBlocks=kK/256;
static constexpr uint32_t kDefaultDownWmmaMinCount=8; // guess only; sweep decides
static_assert(kQ8KBlocks==8, "Flash down K must be eight Q8_K blocks");
static_assert(kN%64==0, "WMMA I=64 output-row tiling requires an exact Flash N");

// Verbatim bodies from current ds4-upstream/rocm/ds4_rocm_moe.cuh:988-1082.
__global__ static void down_count_pairs(uint32_t*c,const int32_t*s,uint32_t np,uint32_t ne){uint32_t p=(uint32_t)((uint64_t)blockIdx.x*blockDim.x+threadIdx.x);if(p>=np)return;int32_t e=s[p];if(e<0)e=0;if((uint32_t)e<ne)atomicAdd(c+(uint32_t)e,1u);}
__global__ static void down_prefix_pairs(uint32_t*o,uint32_t*cur,const uint32_t*c,uint32_t ne){if(threadIdx.x==0){uint32_t sum=0;for(uint32_t e=0;e<ne;++e){o[e]=sum;cur[e]=sum;sum+=c[e];}o[ne]=sum;}}
__global__ static void down_scatter_pairs(uint32_t*pairs,const uint32_t*o,const int32_t*s,uint32_t np,uint32_t ne){uint32_t e=blockIdx.x;if(e>=ne||threadIdx.x)return;uint32_t pos=o[e];for(uint32_t p=0;p<np;++p){int32_t x=s[p];if(x<0)x=0;if((uint32_t)x==e)pairs[pos++]=p;}}
__global__ static void down_tile_offsets(uint32_t*to,uint32_t*total,const uint32_t*c,uint32_t bm,uint32_t ne){if(threadIdx.x==0){uint32_t sum=0;for(uint32_t e=0;e<ne;++e){to[e]=sum;sum+=(c[e]+bm-1)/bm;}to[ne]=sum;*total=sum;}}
__global__ static void down_build_tiles(uint32_t*te,uint32_t*ts,const uint32_t*to,const uint32_t*c,uint32_t bm,uint32_t ne){uint32_t e=(uint32_t)((uint64_t)blockIdx.x*blockDim.x+threadIdx.x);if(e>=ne)return;uint32_t n=(c[e]+bm-1)/bm;for(uint32_t t=0;t<n;++t){te[to[e]+t]=e;ts[to[e]+t]=t*bm;}}

// Faithful copy of the production q8_K_quantize_kernel algorithm (current
// ds4-upstream/rocm/ds4_rocm_moe.cuh:483-529), renamed because the standalone
// Stage-0 include intentionally does not pull in production headers.
__global__ static void down_q8_K_quantize(cuda_block_q8_K*out,const float*x,uint32_t dim,uint32_t rows){uint32_t b=blockIdx.x,row=blockIdx.y;if(row>=rows||b>=dim/256)return;const float*xr=x+(uint64_t)row*dim+(uint64_t)b*256;cuda_block_q8_K*y=out+(uint64_t)row*(dim/256)+b;__shared__ float ap[256],vp[256],isc;uint32_t t=threadIdx.x;float v=t<256?xr[t]:0;ap[t]=t<256?fabsf(v):0;vp[t]=v;__syncthreads();for(uint32_t s=blockDim.x>>1;s;s>>=1){if(t<s&&ap[t+s]>ap[t]){ap[t]=ap[t+s];vp[t]=vp[t+s];}__syncthreads();}float am=ap[0];if(am==0){if(t==0)y->d=0;if(t<256)y->qs[t]=0;if(t<16)y->bsums[t]=0;return;}if(t==0)isc=-127.0f/vp[0];__syncthreads();if(t<256){int q=(int)lrintf(isc*xr[t]);q=q>127?127:(q< -128?-128:q);y->qs[t]=(int8_t)q;}__syncthreads();if(t<16){int sum=0;for(int i=0;i<16;++i)sum+=y->qs[t*16+i];y->bsums[t]=(int16_t)sum;}if(t==0)y->d=1.0f/isc;}

// Down adaptation of the validated q4k_wmma_routed_kernel.  LDS is one
// J=16 pair tile (16*36 ints) plus one I=64 output-row tile (64*76 ints):
// 21,760 bytes, independent of total K/N.  K=2048 is expressed by xb=8;
// conversion makes 2 Q8_1 blocks per Q8_K block, so the loop consumes exactly
// 16 128-value MMQ activation blocks.  N=4096 is grid.x=4096/64=64.
template<int J>
__global__ __launch_bounds__(256) static void down_q4k_wmma(
 const cuda_block_q4_K*w,const q8_1_mmq_block*a,float*out,
 const uint32_t*pairs,const uint32_t*offs,const uint32_t*counts,
 const uint32_t*tile_total,const uint32_t*tile_experts,const uint32_t*tile_starts,
 uint32_t activation_rows,uint32_t xb,uint32_t nrows,uint32_t ne,
 uint32_t threshold,uint32_t*dispatch,uint32_t*marks){
 constexpr int I=64,XS=76,YS=36;extern __shared__ int32_t sm[];int32_t*sy=sm,*sx=sy+J*YS;int tid=threadIdx.x,wave=tid>>5,lane=tid&31;uint32_t tile=blockIdx.y;if(tile>=*tile_total)return;uint32_t expert=tile_experts[tile],start=tile_starts[tile],count=counts[expert];if(count<threshold){if(dispatch&&blockIdx.x==0&&tid==0)atomicAdd(dispatch+1,1u);return;}if(dispatch&&blockIdx.x==0&&tid==0)atomicAdd(dispatch,1u);uint32_t row0=blockIdx.x*I;float acc[J/16][8]={};
 for(uint32_t kb=0;kb<xb;++kb){
  if(wave<8){int r=wave*8+lane/4,tx=(lane%4)*8;if(row0+r<nrows){const auto&ww=w[((uint64_t)expert*nrows+row0+r)*xb+kb];for(int q=0;q<8;++q){int v=*reinterpret_cast<const int32_t*>(ww.qs+4*(tx+q));sx[r*XS+16*((tx+q)/8)+(tx+q)%8]=(v>>0)&0x0f0f0f0f;sx[r*XS+16*((tx+q)/8)+(tx+q)%8+8]=(v>>4)&0x0f0f0f0f;}}}
  if(wave<4){int r=wave*16+lane/2;if(row0+r<nrows){const auto&ww=w[((uint64_t)expert*nrows+row0+r)*xb+kb];int ksc=lane&1,sc32=unpack_q4k_scales(reinterpret_cast<const int*>(ww.scales),ksc),m32=unpack_q4k_scales(reinterpret_cast<const int*>(ww.scales),ksc+2);const uint8_t*sc=(const uint8_t*)&sc32,*mn=(const uint8_t*)&m32;float wd=__half2float(*reinterpret_cast<const half*>(&ww.d)),wm=__half2float(*reinterpret_cast<const half*>(&ww.dmin));for(int l=0;l<4;++l)reinterpret_cast<half2*>(sx+r*XS+64)[4*ksc+l]=__floats2half2_rn(wd*sc[l],-wm*mn[l]);}}
  __syncthreads();
  for(int h=0;h<2;++h){for(int l=tid;l<J*YS;l+=256){int j=l/YS,e=l%YS;uint32_t lp=start+j;if(lp<count){uint32_t pair=pairs[offs[expert]+lp];const int32_t*src=(const int32_t*)&a[((uint64_t)kb*2+h)*activation_rows+pair];sy[l]=src[e];}else sy[l]=0;}__syncthreads();
   if(wave<4)for(int kk=0;kk<4;++kk){auto A=load_rdna3_mirrored_16x8(sx+wave*16*XS+h*32+kk*8,XS);for(int j0=0;j0<J;j0+=16){auto B=load_rdna3_mirrored_16x8(sy+j0*YS+4+kk*8,YS);i32x8 c={};c=wmma_i8_16x16x16(A,B,c);for(int l=0;l<8;++l){int i=2*l+lane/16,j=j0+lane%16;float2 bd=__half22float2(reinterpret_cast<const half2*>(sy+j*YS)[kk]);float2 ad=__half22float2(reinterpret_cast<const half2*>(sx+(wave*16+i)*XS+64)[h*4+kk]);acc[j0/16][l]+=ad.x*bd.x*(float)c[l]+ad.y*bd.y;}}}__syncthreads();}}
 if(wave<4)for(int j0=0;j0<J;j0+=16)for(int l=0;l<8;++l){uint32_t row=row0+wave*16+2*l+lane/16,lp=start+j0+lane%16;if(row<nrows&&lp<count){uint32_t pair=pairs[offs[expert]+lp];uint64_t o=(uint64_t)pair*nrows+row;out[o]=acc[j0/16][l];if(marks)atomicAdd(marks+o,1u);}}
}

// Shipping tile8 math and pair-major store, adapted only to consume the shared
// tile16 stream as two tile8 halves and to add complementary threshold checks.
__global__ static void down_q4k_dp4a_cold(float*out,const char*base,const cuda_block_q8_K*midq,const uint32_t*pairs,const uint32_t*offs,const uint32_t*counts,const uint32_t*total,const uint32_t*te,const uint32_t*ts,uint64_t expert_bytes,uint64_t row_bytes,uint32_t xb,uint32_t nrows,uint32_t threshold,uint32_t*dispatch,uint32_t*marks){uint32_t tile=blockIdx.y;if(tile>=*total)return;uint32_t expert=te[tile],count=counts[expert];if(count>=threshold){if(dispatch&&blockIdx.x==0&&threadIdx.x==0)atomicAdd(dispatch+3,1u);return;}if(dispatch&&blockIdx.x==0&&threadIdx.x==0)atomicAdd(dispatch+2,1u);uint32_t lane=threadIdx.x&7,row=blockIdx.x*32+(threadIdx.x>>3),start=ts[tile];__shared__ cuda_block_q8_K sq[8][8];for(uint32_t h=0;h<2;++h){uint32_t pair[8]={},np=0;const cuda_block_q8_K*x[8]={};for(;np<8;++np){uint32_t lp=start+h*8+np;if(lp>=count)break;pair[np]=pairs[offs[expert]+lp];x[np]=midq+(uint64_t)pair[np]*xb;}for(uint32_t i=threadIdx.x;i<np*xb;i+=blockDim.x){uint32_t p=i/xb,b=i-p*xb;sq[p][b]=x[p][b];}__syncthreads();for(uint32_t p=0;p<np;++p)x[p]=sq[p];if(row<nrows){const cuda_block_q4_K*wr=(const cuda_block_q4_K*)(base+(uint64_t)expert*expert_bytes+(uint64_t)row*row_bytes);float acc[8]={};for(uint32_t b=lane;b<xb;b+=8)dev_dot_q4_K_q8_K_block8(wr+b,x[0]?x[0]+b:NULL,x[1]?x[1]+b:NULL,x[2]?x[2]+b:NULL,x[3]?x[3]+b:NULL,x[4]?x[4]+b:NULL,x[5]?x[5]+b:NULL,x[6]?x[6]+b:NULL,x[7]?x[7]+b:NULL,np,acc);for(uint32_t p=0;p<np;++p){acc[p]=quarter_warp_sum_f32(acc[p],lane);if(lane==0){uint64_t o=(uint64_t)pair[p]*nrows+row;out[o]=acc[p];if(marks)atomicAdd(marks+o,2u);}}}__syncthreads();}}

__global__ static void down_sum_pairs(float*out,const float*pair_out,uint32_t nrows,uint32_t used,uint32_t nt){uint64_t i=(uint64_t)blockIdx.x*blockDim.x+threadIdx.x,n=(uint64_t)nt*nrows;if(i>=n)return;uint32_t tok=i/nrows,row=i-tok*nrows;float v=0;for(uint32_t s=0;s<used;++s)v+=pair_out[((uint64_t)tok*used+s)*nrows+row];out[i]=v;}

static void host_quant_q8k(const std::vector<float>&x,std::vector<cuda_block_q8_K>&q,uint32_t rows){q.resize((size_t)rows*kQ8KBlocks);for(uint32_t r=0;r<rows;++r)for(uint32_t b=0;b<kQ8KBlocks;++b){auto&y=q[(size_t)r*kQ8KBlocks+b];const float*p=x.data()+((size_t)r*kK+b*256);uint32_t mi=0;for(uint32_t i=1;i<256;++i)if(fabsf(p[i])>fabsf(p[mi]))mi=i;if(p[mi]==0){memset(&y,0,sizeof(y));continue;}float is=-127.0f/p[mi];for(uint32_t i=0;i<256;++i){int v=(int)lrintf(is*p[i]);v=std::max(-128,std::min(127,v));y.qs[i]=(int8_t)v;}for(uint32_t s=0;s<16;++s){int v=0;for(uint32_t i=0;i<16;++i)v+=y.qs[s*16+i];y.bsums[s]=(int16_t)v;}y.d=1.0f/is;}}
static float down_host_f16(uint16_t bits){half h;memcpy(&h,&bits,sizeof(h));return __half2float(h);}
static void down_host_scale_min(uint32_t j,const uint8_t*s,uint8_t&sc,uint8_t&mn){if(j<4){sc=s[j]&63u;mn=s[j+4]&63u;}else{sc=(s[j+4]&15u)|((s[j-4]>>6u)<<4u);mn=(s[j+4]>>4u)|((s[j]>>6u)<<4u);}}
static float down_host_q4k_q8k(const cuda_block_q4_K*w,const cuda_block_q8_K*x,uint32_t xb){float acc=0;for(uint32_t b=0;b<xb;++b){int isum=0,summs=0;for(uint32_t j=0;j<8;++j){uint8_t sc,mn;down_host_scale_min(j,w[b].scales,sc,mn);int dot=0,qsum=0;uint32_t bo=(j>>1u)*32u,shift=(j&1u)?4u:0u;for(uint32_t k=0;k<32;++k){int q=(w[b].qs[bo+k]>>shift)&15,a=x[b].qs[j*32u+k];dot+=q*a;qsum+=a;}isum+=(int)sc*dot;summs+=(int)mn*qsum;}acc+=x[b].d*(down_host_f16(w[b].d)*(float)isum-down_host_f16(w[b].dmin)*(float)summs);}return acc;}
// Independent scalar emulation of the Q8_1 arithmetic consumed by WMMA.
// Every 32-value group uses fp16-rounded (weight_scale, weight_min), and the
// converter's fp16-rounded (q8_K.d, q8_K.d*sum).  This distinguishes a loader,
// coordinate, or K-loop bug from the expected Q8_K->Q8_1 format conversion.
static float down_host_q4k_q81(const cuda_block_q4_K*w,const cuda_block_q8_K*x,uint32_t xb,double*sabs_out=nullptr){float acc=0;double sabs=0;for(uint32_t b=0;b<xb;++b){float wd=down_host_f16(w[b].d),wm=down_host_f16(w[b].dmin);for(uint32_t j=0;j<8;++j){uint8_t sc,mn;down_host_scale_min(j,w[b].scales,sc,mn);int dot=0,qsum=0;uint32_t bo=(j>>1u)*32u,shift=(j&1u)?4u:0u;for(uint32_t k=0;k<32;++k){int q=(w[b].qs[bo+k]>>shift)&15,a=x[b].qs[j*32u+k];dot+=q*a;qsum+=a;}half hs=__float2half_rn(wd*(float)sc),hm=__float2half_rn(-wm*(float)mn),hd=__float2half_rn(x[b].d),hds=__float2half_rn(x[b].d*(float)qsum);float t1=__half2float(hs)*__half2float(hd)*(float)dot,t2=__half2float(hm)*__half2float(hds);acc+=t1+t2;if(sabs_out)sabs+=fabs((double)t1)+fabs((double)t2);}}if(sabs_out)*sabs_out=sabs;return acc;}
static void host_reference(const std::vector<cuda_block_q4_K>&w,const std::vector<cuda_block_q8_K>&q,const std::vector<int32_t>&sel,uint32_t ne,std::vector<float>&q8pair,std::vector<float>&q81pair,std::vector<float>&q81sum,std::vector<double>&q81sabs){uint32_t pc=sel.size(),nt=pc/kUsed;q8pair.resize((size_t)pc*kN);q81pair.resize(q8pair.size());q81sabs.resize(q8pair.size());q81sum.assign((size_t)nt*kN,0);for(uint32_t p=0;p<pc;++p){uint32_t e=(uint32_t)std::max(sel[p],0);for(uint32_t row=0;row<kN;++row){const cuda_block_q4_K*wr=w.data()+((size_t)e*kN+row)*kQ8KBlocks;const cuda_block_q8_K*xr=q.data()+(size_t)p*kQ8KBlocks;double sabs=0;float v8=down_host_q4k_q8k(wr,xr,kQ8KBlocks),v81=down_host_q4k_q81(wr,xr,kQ8KBlocks,&sabs);size_t o=(size_t)p*kN+row;q8pair[o]=v8;q81pair[o]=v81;q81sabs[o]=sabs;q81sum[(size_t)(p/kUsed)*kN+row]+=v81;}}(void)ne;}
static bool close_down(const char*tag,const std::vector<float>&a,const std::vector<float>&b){uint64_t bad=0;double md=0;for(size_t i=0;i<a.size();++i){double d=fabs((double)a[i]-b[i]);md=std::max(md,d);if(!std::isfinite(a[i])||d>.05+.01*fabs((double)b[i]))++bad;}printf("  %-12s bad=%llu/%zu max_abs=%.6g\n",tag,(unsigned long long)bad,a.size(),md);return bad==0;}
static bool close_down_core(const char*tag,const std::vector<float>&a,const std::vector<float>&b,double at=1e-3){uint64_t bad=0;double md=0;for(size_t i=0;i<a.size();++i){double d=fabs((double)a[i]-b[i]);md=std::max(md,d);if(!std::isfinite(a[i])||d>at+1e-5*fabs((double)b[i]))++bad;}printf("  %-12s bad=%llu/%zu max_abs=%.6g\n",tag,(unsigned long long)bad,a.size(),md);return bad==0;}
// Cancellation-aware WMMA-vs-Q8_1 comparator: tol = 2*gamma_67*sum_abs_terms
// (Higham forward-error bound, n=67 fp32 ops per element: two scale/dot
// multiplies + one combine + up to 64 accumulation adds). The fixed
// atol+rtol*|ref| form is the wrong shape here because rounding error
// scales with the sum of magnitudes of the 64 contributing terms, not with
// the (possibly cancelled-down) reference value itself. No rounding-boundary
// exception needed: this is continuous fp32 reduction error, not a discrete
// quantizer classification.
static constexpr double kGamma67=(67.0*0x1p-24)/(1.0-67.0*0x1p-24);
static bool close_down_gamma(const char*tag,const std::vector<float>&a,const std::vector<float>&b,const std::vector<double>&sabs,const std::vector<int32_t>&sel){uint64_t bad=0;double md=0;uint32_t shown=0;for(size_t i=0;i<a.size();++i){double d=fabs((double)a[i]-b[i]),tol=2.0*kGamma67*sabs[i];md=std::max(md,d);if(!std::isfinite(a[i])||d>tol){++bad;if(shown<16){uint32_t pair=(uint32_t)(i/kN),row=(uint32_t)(i%kN);int32_t expert=pair<sel.size()?sel[pair]:-1;float ga=a[i],gb=(float)b[i];uint32_t ua,ub;memcpy(&ua,&ga,4);memcpy(&ub,&gb,4);int64_t ulp=(int64_t)ua-(int64_t)ub;printf("    WMMA-vs-Q8_1-MISMATCH pair=%u expert=%d row=%u gpu=%.9g cpu=%.9g diff=%.9g ulp=%lld sum_abs_terms=%.9g tol=%.9g ratio=%.4f\n",pair,expert,row,(double)a[i],(double)b[i],d,(long long)ulp,sabs[i],tol,tol>0?d/tol:INFINITY);++shown;}}}printf("  %-12s bad=%llu/%zu max_abs=%.6g\n",tag,(unsigned long long)bad,a.size(),md);return bad==0;}
struct q8k_check{bool exact,valid;uint64_t qdiff,scale_diff,bad_bsum,off_boundary;int max_qdiff;double max_scale_diff,max_boundary_distance;};
static q8k_check check_q8k(const std::vector<cuda_block_q8_K>&gpu,const std::vector<cuda_block_q8_K>&host,const std::vector<float>&mid){q8k_check z={gpu.size()==host.size(),gpu.size()==host.size(),0,0,0,0,0,0,0};if(gpu.size()!=host.size()||mid.size()!=gpu.size()*256){z.valid=false;return z;}for(size_t b=0;b<gpu.size();++b){double dd=fabs((double)gpu[b].d-host[b].d);z.max_scale_diff=std::max(z.max_scale_diff,dd);if(dd!=0){++z.scale_diff;z.exact=false;}for(int i=0;i<256;++i){int d=abs((int)gpu[b].qs[i]-(int)host[b].qs[i]);z.max_qdiff=std::max(z.max_qdiff,d);if(d){++z.qdiff;z.exact=false;double scaled=(double)mid[b*256+i]/(double)gpu[b].d,frac=fabs(scaled-nearbyint(scaled)),bd=fabs(.5-frac);z.max_boundary_distance=std::max(z.max_boundary_distance,bd);if(d>1||bd>4e-5){++z.off_boundary;z.valid=false;}}}for(int s=0;s<16;++s){int sum=0;for(int i=0;i<16;++i)sum+=gpu[b].qs[s*16+i];if(sum!=gpu[b].bsums[s]){++z.bad_bsum;z.valid=false;}}if(dd>2e-7*std::max(1.0,fabs((double)host[b].d)))z.valid=false;}return z;}
static std::vector<int32_t> from_counts(const std::vector<uint32_t>&c){std::vector<int32_t>v;for(uint32_t e=0;e<c.size();++e)for(uint32_t i=0;i<c[e];++i)v.push_back((int32_t)e);return v;}
static std::vector<int32_t> formula(uint32_t nt,uint32_t ne,bool skew){std::vector<int32_t>v(nt*kUsed);for(uint32_t p=0;p<v.size();++p)v[p]=skew?(int32_t)((p%kUsed)?(p/kUsed+p%kUsed)%std::min(ne,7u):0):(int32_t)(p%ne);return v;}
static std::vector<int32_t> zipf(uint32_t n,uint32_t ne){std::vector<double>w(ne);for(uint32_t i=0;i<ne;++i)w[i]=1.0/pow((double)i+1,1.2);std::mt19937 g(0x444f574e);std::discrete_distribution<uint32_t>d(w.begin(),w.end());std::vector<int32_t>v(n);for(auto&x:v)x=(int32_t)d(g);return v;}

struct Timing{uint32_t bucket,threshold;double candidate,shipping;};static std::vector<Timing> timings;
static bool run_down_case(const char*name,uint32_t nt,uint32_t ne,const std::vector<int32_t>&sel,const std::vector<uint32_t>&thresholds,uint32_t timing_bucket=0){uint32_t pc=nt*kUsed;if(sel.size()!=pc){fprintf(stderr,"bad case size %s\n",name);return false;}std::mt19937 rng(0xd04e0000u+nt+ne);std::vector<float>mid((size_t)pc*kK);std::normal_distribution<float>md(0,.20f);for(auto&v:mid)v=std::max(-3.0f,std::min(3.0f,md(rng)));std::vector<cuda_block_q8_K>hq;host_quant_q8k(mid,hq,pc);std::vector<cuda_block_q4_K>hw((size_t)ne*kN*kQ8KBlocks);for(auto&b:hw)fill_q4_K_block(&b,rng);std::vector<float>cpu_q8_pair,cpu_q81_pair,cpu_q81_sum;std::vector<double>cpu_q81_sabs;
 int32_t*ds;uint32_t *dc,*doo,*dcur,*dsp,*dto,*dtt,*dte,*dts,*marks,*disp;float *dm,*ref,*cand,*toksum;cuda_block_q8_K*dq8;q8_1_mmq_block*dq81;cuda_block_q4_K*dw;size_t ps=(size_t)pc*kN*4,ms=(size_t)pc*kN*4;
 #define DMALLOC(p,n,s) hip_check(hipMalloc(&(p),(n)),s)
 DMALLOC(ds,pc*4,"selected");DMALLOC(dc,ne*4,"counts");DMALLOC(doo,(ne+1)*4,"offsets");DMALLOC(dcur,ne*4,"cursors");DMALLOC(dsp,pc*4,"pairs");DMALLOC(dto,(ne+1)*4,"tile offsets");DMALLOC(dtt,4,"tile total");DMALLOC(dte,pc*4,"tile experts");DMALLOC(dts,pc*4,"tile starts");DMALLOC(dm,mid.size()*4,"mid f32");DMALLOC(dq8,hq.size()*sizeof(*dq8),"mid q8k");DMALLOC(dq81,(size_t)pc*kQ8KBlocks*2*sizeof(*dq81),"mid q81");DMALLOC(dw,hw.size()*sizeof(*dw),"weights");DMALLOC(ref,ps+4,"shipping out");DMALLOC(cand,ps+4,"candidate out");DMALLOC(toksum,(size_t)nt*kN*4+4,"sum out");DMALLOC(marks,ms+4,"markers");DMALLOC(disp,16,"dispatch");
 hip_check(hipMemcpy(ds,sel.data(),pc*4,hipMemcpyHostToDevice),"selected copy");hip_check(hipMemcpy(dm,mid.data(),mid.size()*4,hipMemcpyHostToDevice),"mid copy");hip_check(hipMemcpy(dw,hw.data(),hw.size()*sizeof(*dw),hipMemcpyHostToDevice),"weights copy");hip_check(hipMemset(dc,0,ne*4),"counts clear");down_count_pairs<<<(pc+255)/256,256>>>(dc,ds,pc,ne);down_prefix_pairs<<<1,1>>>(doo,dcur,dc,ne);down_scatter_pairs<<<ne,1>>>(dsp,doo,ds,pc,ne);down_tile_offsets<<<1,1>>>(dto,dtt,dc,16,ne);down_build_tiles<<<(ne+255)/256,256>>>(dte,dts,dto,dc,16,ne);down_q8_K_quantize<<<dim3(kQ8KBlocks,pc),256>>>(dq8,dm,kK,pc);q8_K_to_q8_1_mmq_kernel<<<dim3(pc,kQ8KBlocks),32>>>(dq8,dq81,pc,kQ8KBlocks);hip_check(hipDeviceSynchronize(),"setup");
 std::vector<cuda_block_q8_K>gotq(hq.size());hip_check(hipMemcpy(gotq.data(),dq8,gotq.size()*sizeof(*dq8),hipMemcpyDeviceToHost),"q8 back");q8k_check qc=check_q8k(gotq,hq,mid);host_reference(hw,gotq,sel,ne,cpu_q8_pair,cpu_q81_pair,cpu_q81_sum,cpu_q81_sabs);std::vector<uint32_t>hc(ne),ho(ne+1),hp(pc),hte(pc),hts(pc);uint32_t tiles=0;hip_check(hipMemcpy(hc.data(),dc,ne*4,hipMemcpyDeviceToHost),"counts back");hip_check(hipMemcpy(ho.data(),doo,(ne+1)*4,hipMemcpyDeviceToHost),"offset back");hip_check(hipMemcpy(hp.data(),dsp,pc*4,hipMemcpyDeviceToHost),"pairs back");hip_check(hipMemcpy(&tiles,dtt,4,hipMemcpyDeviceToHost),"total back");hip_check(hipMemcpy(hte.data(),dte,tiles*4,hipMemcpyDeviceToHost),"te back");hip_check(hipMemcpy(hts.data(),dts,tiles*4,hipMemcpyDeviceToHost),"ts back");bool route=ho[ne]==pc;uint32_t et=0;for(uint32_t e=0;e<ne;++e){uint32_t n=0;for(uint32_t p=0;p<pc;++p)if((uint32_t)std::max(sel[p],0)==e)route&=hp[ho[e]+n++]==p;route&=n==hc[e];for(uint32_t s=0;s<hc[e];s+=16){route&=et<tiles&&hte[et]==e&&hts[et]==s;++et;}}route&=et==tiles;
 dim3 wg(kN/64,tiles),dg(kN/32,tiles);size_t sh=(16*36+64*76)*sizeof(int32_t);uint64_t rb=(uint64_t)kQ8KBlocks*sizeof(cuda_block_q4_K),eb=(uint64_t)kN*rb;hip_check(hipMemset(ref,0xff,ps+4),"ref poison");hip_check(hipMemset(cand,0xff,ps+4),"candidate poison");down_q4k_dp4a_cold<<<dg,256>>>(ref,(const char*)dw,dq8,dsp,doo,dc,dtt,dte,dts,eb,rb,kQ8KBlocks,kN,UINT_MAX,NULL,NULL);down_q4k_wmma<16><<<wg,256,sh>>>(dw,dq81,cand,dsp,doo,dc,dtt,dte,dts,pc,kQ8KBlocks,kN,ne,0,NULL,NULL);hip_check(hipDeviceSynchronize(),"gemm");std::vector<float>gr(cpu_q8_pair.size()),gc(cpu_q81_pair.size()),gs(cpu_q81_sum.size());hip_check(hipMemcpy(gr.data(),ref,ps,hipMemcpyDeviceToHost),"ref back");hip_check(hipMemcpy(gc.data(),cand,ps,hipMemcpyDeviceToHost),"candidate back");uint32_t rg=0,cg=0;hip_check(hipMemcpy(&rg,(char*)ref+ps,4,hipMemcpyDeviceToHost),"ref guard");hip_check(hipMemcpy(&cg,(char*)cand+ps,4,hipMemcpyDeviceToHost),"candidate guard");bool ok=qc.valid&&route&&rg==UINT_MAX&&cg==UINT_MAX&&close_down("DP4A-vs-Q8K",gr,cpu_q8_pair)&&close_down_gamma("WMMA-vs-Q8_1",gc,cpu_q81_pair,cpu_q81_sabs,sel);close_down("Q8_1-vs-Q8K",cpu_q81_pair,cpu_q8_pair);down_sum_pairs<<<((uint64_t)nt*kN+255)/256,256>>>(toksum,cand,kN,kUsed,nt);hip_check(hipDeviceSynchronize(),"sum");hip_check(hipMemcpy(gs.data(),toksum,gs.size()*4,hipMemcpyDeviceToHost),"sum back");ok&=close_down_core("sum-vs-Q8_1",gs,cpu_q81_sum,6e-3);printf("  q8K-check exact=%s valid=%s qdiff=%llu max_qdiff=%d scale_diff=%llu max_scale_diff=%.9g bad_bsum=%llu\n",qc.exact?"yes":"no",qc.valid?"yes":"no",(unsigned long long)qc.qdiff,qc.max_qdiff,(unsigned long long)qc.scale_diff,qc.max_scale_diff,(unsigned long long)qc.bad_bsum);printf("CASE %-20s route=%s q8K-faithful=%s result=%s\n",name,route?"PASS":"FAIL",qc.valid?"PASS":"FAIL",ok?"PASS":"FAIL");
 for(uint32_t th:thresholds){hip_check(hipMemset(cand,0xff,ps+4),"cross poison");hip_check(hipMemset(marks,0,ms+4),"marks clear");hip_check(hipMemset(disp,0,16),"dispatch clear");down_q4k_wmma<16><<<wg,256,sh>>>(dw,dq81,cand,dsp,doo,dc,dtt,dte,dts,pc,kQ8KBlocks,kN,ne,th,disp,marks);down_q4k_dp4a_cold<<<dg,256>>>(cand,(const char*)dw,dq8,dsp,doo,dc,dtt,dte,dts,eb,rb,kQ8KBlocks,kN,th,disp,marks);hip_check(hipDeviceSynchronize(),"crossover");hip_check(hipMemcpy(gc.data(),cand,ps,hipMemcpyDeviceToHost),"cross back");std::vector<uint32_t>hm((size_t)pc*kN);uint32_t hd[4],mg=1,og=0;hip_check(hipMemcpy(hm.data(),marks,ms,hipMemcpyDeviceToHost),"marks back");hip_check(hipMemcpy(hd,disp,16,hipMemcpyDeviceToHost),"dispatch back");hip_check(hipMemcpy(&mg,(char*)marks+ms,4,hipMemcpyDeviceToHost),"mark guard");hip_check(hipMemcpy(&og,(char*)cand+ps,4,hipMemcpyDeviceToHost),"output guard");uint32_t hot=0,cold=0;for(uint32_t t=0;t<tiles;++t)(hc[hte[t]]>=th?hot:cold)++;bool own=mg==0&&og==UINT_MAX&&hd[0]==hot&&hd[1]==cold&&hd[2]==cold&&hd[3]==hot;for(uint32_t p=0;p<pc;++p){uint32_t want=hc[(uint32_t)std::max(sel[p],0)]>=th?1:2;for(uint32_t r=0;r<kN;++r)own&=hm[(size_t)p*kN+r]==want;}std::vector<float>cross_cpu=cpu_q8_pair;for(uint32_t p=0;p<pc;++p)if(hc[(uint32_t)std::max(sel[p],0)]>=th)std::copy_n(cpu_q81_pair.data()+(size_t)p*kN,kN,cross_cpu.data()+(size_t)p*kN);ok&=own&&close_down_core("cross-vs-CPU",gc,cross_cpu);printf("  threshold=%u hot/cold=%u/%u ownership+guards=%s\n",th,hot,cold,own?"PASS":"FAIL");if(timing_bucket){auto candidate=[&](){down_q8_K_quantize<<<dim3(kQ8KBlocks,pc),256>>>(dq8,dm,kK,pc);q8_K_to_q8_1_mmq_kernel<<<dim3(pc,kQ8KBlocks),32>>>(dq8,dq81,pc,kQ8KBlocks);down_q4k_wmma<16><<<wg,256,sh>>>(dw,dq81,cand,dsp,doo,dc,dtt,dte,dts,pc,kQ8KBlocks,kN,ne,th,NULL,NULL);down_q4k_dp4a_cold<<<dg,256>>>(cand,(const char*)dw,dq8,dsp,doo,dc,dtt,dte,dts,eb,rb,kQ8KBlocks,kN,th,NULL,NULL);down_sum_pairs<<<((uint64_t)nt*kN+255)/256,256>>>(toksum,cand,kN,kUsed,nt);};auto shipping=[&](){down_q8_K_quantize<<<dim3(kQ8KBlocks,pc),256>>>(dq8,dm,kK,pc);down_q4k_dp4a_cold<<<dg,256>>>(ref,(const char*)dw,dq8,dsp,doo,dc,dtt,dte,dts,eb,rb,kQ8KBlocks,kN,UINT_MAX,NULL,NULL);down_sum_pairs<<<((uint64_t)nt*kN+255)/256,256>>>(toksum,ref,kN,kUsed,nt);};BenchResult a=time_launch(candidate),b=time_launch(shipping);timings.push_back({timing_bucket,th,a.median_us,b.median_us});printf("  timing bucket=%u threshold=%u candidate=%.3fus shipping=%.3fus speedup=%.4fx\n",timing_bucket,th,a.median_us,b.median_us,b.median_us/a.median_us);}}
 #define DFREE(p) (void)hipFree(p)
 DFREE(ds);DFREE(dc);DFREE(doo);DFREE(dcur);DFREE(dsp);DFREE(dto);DFREE(dtt);DFREE(dte);DFREE(dts);DFREE(dm);DFREE(dq8);DFREE(dq81);DFREE(dw);DFREE(ref);DFREE(cand);DFREE(toksum);DFREE(marks);DFREE(disp);return ok;}

static void report_sweep(const std::vector<uint32_t>&ths){printf("\nDOWN CROSSOVER SWEEP (starting guess=%u; measurements decide)\n",kDefaultDownWmmaMinCount);for(uint32_t th:ths){double logs=0;uint32_t n=0;bool regress=false;for(const auto&t:timings)if(t.threshold==th&&t.bucket>=th){double s=t.shipping/t.candidate;logs+=log(s);++n;regress|=t.candidate>1.05*t.shipping;}printf("  threshold=%2u retained=%u geomean=%s",th,n,n?"":"UNMEASURED\n");if(n)printf("%.4fx regression_gt_5pct=%s gate=%s\n",exp(logs/n),regress?"YES":"no",exp(logs/n)>=1.20&&!regress?"PASS":"FAIL");}}

int main(int argc,char**argv){uint32_t guess=kDefaultDownWmmaMinCount;if(argc>1)guess=(uint32_t)strtoul(argv[1],NULL,10);std::vector<uint32_t>ths={1,2,4,6,8,12,16,24,32};if(std::find(ths.begin(),ths.end(),guess)==ths.end())ths.push_back(guess);std::sort(ths.begin(),ths.end());bool ok=true;ok&=run_down_case("balanced",17,256,formula(17,256,false),{guess});ok&=run_down_case("skewed",23,256,formula(23,256,true),{guess});ok&=run_down_case("tile-edges",14,16,from_counts({1,7,8,9,15,16,17,11}),{guess});ok&=run_down_case("interleaved-empty",8,16,from_counts({6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0}),{guess});ok&=run_down_case("all-256-active",256,256,from_counts(std::vector<uint32_t>(256,6)),{guess});ok&=run_down_case("zipf-s1.2-proxy",256,256,zipf(1536,256),{guess});std::vector<int32_t>rep(24,1);for(uint32_t p=0;p<17;++p)rep[p]=0;ok&=run_down_case("repeated-boundary",4,8,rep,{guess});for(uint32_t m:std::vector<uint32_t>{1,4,6,8,12,16,24,32,64}){char n[48];snprintf(n,sizeof(n),"timing-bucket-%u",m);ok&=run_down_case(n,m,6,from_counts(std::vector<uint32_t>(6,m)),ths,m);}report_sweep(ths);printf("down routed validation (not a timing gate until run on gfx1151): %s\n",ok?"PASS":"FAIL");return ok?0:1;}
